services:
  next-app:
    image: node:latest
    container_name: cook_next_app
    command: /bin/sh -c "cd /app/cook-app npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app/cook-app
    environment:
      - WATCHPACK_POLLING=true
    volumes:
    - type: bind
      source: ./lethimcook-app
      target: /app/cook-app
    tty: true
    networks:
      - cook_network
  
  ollama:
    container_name: cook_ollama_next
    image: ollama/ollama
    ports:
      - "8080:11434"
    networks:
      - cook_network

networks:
  cook_network: {}
